### ISSUE TITLE
Tune ringboard-x11.service

### ISSUE THREAD

**Issue by hedgieinsocks** [SUPERCILEX/clipboard-history#19]
Hi! Being on gnome wayland, I've installed it via curl oneliner, and after a reboot I noticed that the x11 watcher does not work. It turns out sometimes it fails the `ConditionEnvironment=DISPLAY` after a reboot and gets stuck. And sometimes it just gets stuck due to too many failures on boot. So I've just commented out `ConditionEnvironment=DISPLAY` and added `RestartSec=1` which solved my issue. Perhaps you'll come up with a more elegant solution ;)

**Comment by SUPERCILEX** [comment]
Dang, mine has never failed but then again I'm still on X11.

The goal with that condition is just to prevent the watcher from trying to start if no X11 server is present, so I need to figure out a way to add that dependency explicitly instead of this hacky stuff.

**Comment by SUPERCILEX** [comment]
There's a bunch of reading here I'll look at tomorrow: https://wiki.archlinux.org/title/Systemd/User

**Comment by SUPERCILEX** [comment]
I just updated the service files. Can you give it another go? I think the bug is that I had a dependency on `graphical` rather than `graphical-session`.

**Comment by hedgieinsocks** [comment]
I confirm that the service now starts without issues after reboot. Thank you! 

Now, unrelated stuff, I've tried egui and have a couple of things to bring up:

* egui window does not want to get closed, and I believe it briefly shows a popup saying 'nothing to see here' when clicked
* when you select an item in egui, it automatically scrolls up, and this results in a flicker if you are selecting an item close to the search bar (cause there is nowhere to scroll I guess)... not sure that this auto-scroll to the top is required at all cause it does not seem to play any logical role
* the search bar is using smaller font and its height is smaller than the height of the selected line, I suggest that you try at least the same font size or even bigger search bar height to make it stand out as the main interaction point

**Comment by SUPERCILEX** [comment]
> egui window does not want to get closed

What does this mean exactly? The process is supposed to stay alive, but all the UI should disappear and be hidden until you trigger a reopen. I'll need to double check the flicker.


Will look into the other bugs tomorrow.
---

This is great feedback BTW, thank you!

**Comment by hedgieinsocks** [comment]
https://github.com/user-attachments/assets/f7e94913-8517-494d-bdcc-e98e0c7763f9

**Comment by SUPERCILEX** [comment]
Thanks for the video! I think issue 1 and 2 are the same. What's supposed to happen is the window closes and the UI completely unloads to save memory. Then when you reopen, the app does a full reload which would explain the "scrolling" (in reality everything is reset). Probs a wayland bug, lemme look into it.

**Comment by hedgieinsocks** [comment]
Yeah, most likely as always. By the way, it's not related to the recent refactor, egui did not close for me from the initial release.

**Comment by SUPERCILEX** [comment]
Well this is dumb but wayland just straight up doesn't support it: https://github.com/rust-windowing/winit/issues/2388

You'll need to `cargo +nightly install clipboard-history-egui --no-default-features --features wayland` to make sure you get the fix. Wait for deployment first: https://github.com/SUPERCILEX/clipboard-history/actions/runs/10271223333

**Comment by SUPERCILEX** [comment]
Oh holy shit actually wayland startup is ridiculously fast so you don't really need my quick start stuff anyway. That makes me happy. Lemme know if anything else is broken. :)

**Comment by hedgieinsocks** [comment]
Yeah, installed v0.4.2 and the window now properly closes. But guess what? Yes, you are right: now it fails to copy the selected entry to the clipboard. It says paste, but I believe it means copy item to the clipboard. Cause the previous x11 version did that (selected entry went into the clipboard), but wayland version does not want us to be happy  ;)
![image](https://github.com/user-attachments/assets/327b550e-d6ac-47e2-a50b-88d76675f8c6)

**Comment by SUPERCILEX** [comment]
Oh for that did you install the latest version of the clipboard watcher and server?
```
cargo +nightly install clipboard-history-x11 --no-default-features
cargo +nightly install clipboard-history-server --no-default-features --features systemd
```

**Comment by SUPERCILEX** [comment]
BTW not sure if you're using https://crates.io/crates/cargo-update but it should make updating easier.

**Comment by SUPERCILEX** [comment]
And does the scrollbar not shrink when not in use? It's supposed to be completely hidden by default and look like this when hovering over the list:
![image](https://github.com/user-attachments/assets/0f5f4068-0a7a-41cb-ac9e-4083284d9057)

Yours looks like the scrollbar when being actively used.

**Comment by hedgieinsocks** [comment]
Actually, scratch my latest bug report. The error was due to failed ringboard-x11.service cause I messed up the /tmp files. It does work as expected now! 

Thanks for cargo-update advise, noted!

The scrollbar complaint was indeed about focused active mode. But I guess it comes with the library.

About theming, it was just curiosity after checking out https://github.com/emilk/egui 
ENV sounds nice, in theory one could launch it like `RNGBRD_THEME=nord ringboard-egui` but it seems that you would need to create hardcoded styles, and the project is not that mature for you to waste yourself on that. Today this, tomorrow native window decorations, then add AI :D

**Comment by hedgieinsocks** [comment]
While the issue is not yet closed, another improvement suggestion: hitting `Esc` should close/hide the window.
Also, I believe in the future you will face more wayland issues due to inability of wayland to remember the size and position of windows (eghhhh disappointment :D)

**Comment by SUPERCILEX** [comment]
> But I guess it comes with the library.

Yeah.

> Today this, tomorrow native window decorations, then add AI :D

Loooool. Well I added a `THEME=light` envvar anyway cuz it's easy to do.

> hitting Esc should close/hide the window

Done. 0.5 will hit the shelves in a few mins.

**Comment by hedgieinsocks** [comment]
Great! It works :D Nice to watch it evolve before your own eyes, keep it up!!

**Comment by SUPERCILEX** [comment]
Hell yeah, thanks for the great suggestions and bug reports!
