### ISSUE TITLE
Cargo Nightly requirnment

### ISSUE THREAD

**Issue by xalt7x** [SUPERCILEX/clipboard-history#20]
I've tried following [installation-instructions](https://github.com/SUPERCILEX/clipboard-history#installation-instructions)

> The easiest way to get going is to [install cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html) and then run the installation script for systemd:
> 
> curl -s https://raw.githubusercontent.com/SUPERCILEX/clipboard-history/master/install-with-cargo-systemd.sh | bash

Cargo installed successfully with `curl https://sh.rustup.rs -sSf | sh`
However,
`curl -s https://raw.githubusercontent.com/SUPERCILEX/clipboard-history/master/install-with-cargo-systemd.sh | bash`
showed
> error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed

Is it leftover just a development leftover or Cargo Nightly is really required?

**Comment by SUPERCILEX** [comment]
Sorry about that, I added some extra instructions. Still required, but easily fixable with `rustup install nightly`. Let me know if you run into any other issues!
