### ISSUE TITLE
"Failed to send paste entry to paste server." on  Gnome 46 X-11

### ISSUE THREAD

**Issue by aflip** [SUPERCILEX/clipboard-history#21]
I am running Ubuntu 24.04 LTS with Gnome 46 with X11 and after following the instructions on the github page, I got the gui up using egui, but am unable to paste anything, this error shows up if I click on any item. 

[
![Screenshot from 2024-08-08 03-12-14](https://github.com/user-attachments/assets/4ddff6c4-09f9-4b56-801a-3eff8355e3d5)
](url)

`Error: an I/O error occurred
Details: Core(
    Io {
        error: Os {
            code: 111,
            kind: ConnectionRefused,
            message: "Connection refused",
        },
        context: "Failed to send paste entry to paste server.",
    }, 
}`

**Comment by SUPERCILEX** [comment]
What outputs when you run `systemctl --user status ringboard-x11`? It's probably just not started.

**Comment by aflip** [comment]
> What outputs when you run `systemctl --user status ringboard-x11`? It's probably just not started.

● ringboard-x11.service - X11 Ringboard clipboard listener
     Loaded: loaded (/home/XXXXXXX/.config/systemd/user/ringboard-x11.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-08-08 02:47:49 IST; 37min ago
       Docs: https://github.com/SUPERCILEX/clipboard-history
   Main PID: 57502 (ringboard-x11)
      Tasks: 1 (limit: 17675)
     Memory: 432.0K (peak: 1.5M)
        CPU: 41ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/ringboard-x11.service
             └─57502 ringboard-x11

Aug 08 03:23:21 XXXXXXX sh[57502]: [INFO  ringboard_x11] Selection notification received.
Aug 08 03:23:21 XXXXXXXX sh[57502]: [INFO  ringboard_x11] Promoting duplicate small selection to front.

**Comment by SUPERCILEX** [comment]
Ah shoot, that looks like a configuration bug then. I just pushed an updated that will show the address it's trying to connect to in egui. You'll want to run `cargo +nightly install clipboard-history-egui --no-default-features --features x11` to update (or just install https://github.com/nabijaczleweli/cargo-update and run `cargo install-update -a` to handle things automatically). Then open egui, try to paste, and now the error message should say which file it's trying to use. Then run `ls /tmp/.ringboard` and we'll see what file `ringboard-x11` is using (it'll be something `.paste`).

**Comment by aflip** [comment]
> `ls /tmp/.ringboard`

Confirming that this is solved. the ls command gives the following output
`Username.ch  Username.egui-sleep  Username.paste`

**Comment by SUPERCILEX** [comment]
Great to hear!
