### ISSUE TITLE
wayland folder missing

### ISSUE THREAD

**Issue by GaetanLepage** [SUPERCILEX/clipboard-history#23]
The README [mentions a `wayland/` directory](https://github.com/SUPERCILEX/clipboard-history/blob/master/README.md?plain=1#L105) which actually doesn't exist.

Where is the code for the wayland watcher ?

Thanks in advance !

**Comment by SUPERCILEX** [comment]
I still need to implement it lol! https://github.com/SUPERCILEX/clipboard-history/issues/10

**Comment by GaetanLepage** [comment]
Oh I see ! Good luck :)
