### ISSUE TITLE
egui ctrl+n using 0-based index instead of 1-based

### ISSUE THREAD

**Issue by ivan-toriya** [SUPERCILEX/clipboard-history#26]
I think it would make more sense to change it to 1-based index when using Ctrl + N to paste the Nth entry.

Also, another feature request is to see this index in the GUI. What do you think?

**Comment by SUPERCILEX** [comment]
The number overlay is a great idea, done. I think it renders the question of indexing obsolete because you can easily see which entry to select, but please let me know if you still think we should be 1 indexing after the update.

**Comment by ivan-toriya** [comment]
I've updated using the `cargo install-update -a` with nightly rust. Restarted. Can't see the indexing. I'm super new to rust, what am I doing wrong? 
![image](https://github.com/user-attachments/assets/ae389ea7-6512-4ab9-a0a6-cee5d66be591)

**Comment by SUPERCILEX** [comment]
Oh it only shows up if you hit Ctrl. Does that work?

**Comment by ivan-toriya** [comment]
Ah, yeah, it works, thanks!

**Comment by SUPERCILEX** [comment]
Yay!
