### ISSUE TITLE
Tui not installed 

### ISSUE THREAD

**Issue by TieWay59** [SUPERCILEX/clipboard-history#30]
I followed the default install instruction: 

![image](https://github.com/user-attachments/assets/4a359da9-762f-4f00-b0d9-f246c96136d7)

```bash
ls -a ringboard*
ringboard  ringboard-egui  ringboard-server  ringboard-x11
```

## env

```bash

uname -a
Linux YTZLDT1810014 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

rustup --version
rustup 1.27.1 (2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`

cargo --version
cargo 1.80.1 (376290515 2024-07-16)
```

**Comment by SUPERCILEX** [comment]
Yup, that's normal. Are you planning on using both tui and egui? I kinda thought I'd only install egui by default and let folks get tui only if they needed it.

**Comment by TieWay59** [comment]
@SUPERCILEX I wish to try Tui to see if some font issues can be avoided. (I have some Chinese font settings in my terminal, but don't know how to configure egui fonts.)

So could you provide an installation hint on the TUI client? 

![image](https://github.com/user-attachments/assets/13b30ceb-f80f-4a8d-a79c-509a2595cfe0)

**Comment by SUPERCILEX** [comment]
Oh if you just want to install it run `cargo install clipboard-history-tui`.

**Comment by TieWay59** [comment]
`cargo +nightly install clipboard-history-tui` 

guess +nightly is required.

BTW, do you plan to change the bin name or project name? I thought I tried `cargo install ringboard-tui` but failed. kinda confusing for a cli tool.

**Comment by SUPERCILEX** [comment]
Oops right, thanks for the reminder about nightly. I wish I'd started out with the packages named ringboard, but the name came a few months after the original idea and sadly there's no way to create crate aliases, I'd just have to publish duplicates. I'll look into it.

**Comment by TieWay59** [comment]
Still, love your work! I'll close this issue for now, it's so nice of you doing this.

**Comment by SUPERCILEX** [comment]
Ok the "aliases" (aka duplicate packages) exist now. That's a good idea to prevent supply chain attacks too, so thanks!
