### ISSUE TITLE
ringboard-x11 fails to restart syscalls after interruption

### ISSUE THREAD

**Issue by vi** [SUPERCILEX/clipboard-history#31]
```
ringboard-x11 &Error: an I/O error occurred
│
╰─▶ Interrupted system call (os error 4)
    ╰╴Failed to wait for epoll events.
```

I think `EINTR` should be just restarted in most of the cases.

Maybe this was caused by suspend-to-ram, maybe by something else.

**Comment by SUPERCILEX** [comment]
I'm a little bit worried about getting stuck in an infinite loop because of this: https://stackoverflow.com/questions/46502099/epoll-wait-returns-eintr-infinitely. But in my testing it seemed fine? I wish that post had figured out the root cause cuz I feel like it's a bug in their code rather than something that can actually happen. Hopefully.

**Comment by vi** [comment]
I typically assume that any syscall that waits for something can spuriously wake with `EINTR`. Sometimes I also handle unexpected `EAGAIN`s (by sleeping a bit before resuming the loop).

**Comment by vi** [comment]
Note: as of commit 1625939dd2a15d5cf668158752486004880b692b `ringboard-server` crashes when I try to start `ringboard-x11`.

```
$ RUST_BACKTRACE=1 target/myrelease/ringboard-server                                                                                    thread 'main' panicked at server/src/reactor.rs:348:21:
index out of bounds: the len is 32 but the index is 34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/panicking.rs:276:5
   3: ringboard_server::reactor::run
             at /mnt/bkel/vi/src/clipboard-history/server/src/reactor.rs:348:21
   4: ringboard_server::run
             at /mnt/bkel/vi/src/clipboard-history/server/src/main.rs:110:13
   5: ringboard_server::main
             at /mnt/bkel/vi/src/clipboard-history/server/src/main.rs:54:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

**Comment by SUPERCILEX** [comment]
Fixed in https://github.com/SUPERCILEX/clipboard-history/commit/3676439b3b4de1c1ee61766efeaea2de5095ee25. Thanks for catching that!
