### ISSUE TITLE
The background color of the hovered/selected row is too bright in light theme

### ISSUE THREAD

**Issue by hedgieinsocks** [SUPERCILEX/clipboard-history#33]
Long time no see :P In the default dark theme, the hovered/selected row is perfectly lighter than others. 

But it does not work well with the light theme, since the selected row becomes white and thus barely noticeable against the already light color scheme.

I believe that the hovered/selected row should be darker in the light theme. 

I guess it could be configured here?

https://github.com/SUPERCILEX/clipboard-history/blob/57a78d75a28a89612b1da3d8e75ba5d8b7a1db55/egui/src/main.rs#L726

**Comment by SUPERCILEX** [comment]
Should be fixed! I also got rid of margins to give the app a tighter look (not quite sure if I like it yet, but it's definitely minimalistic).
