### ISSUE TITLE
Extra border in search bar when egui is launched with light theme 

### ISSUE THREAD

**Issue by hedgieinsocks** [SUPERCILEX/clipboard-history#35]
Uh-oh, yet another 3 tiny things to report ;)

1) When egui is launched in light mode, switch to regex mode, and you will notice that the bottom border of the search box changes its width. To my eye, it looks proper in regex mode, but wrong in the default mode. Interestingly, this visual inconsistency does not seem to be visible in the dark mode.

I'm not sure whether fixing it in light mode will break it in dark, or it's just egui lib thing. But anyway, letting you know my observations. 

2) Apart from that, when you are bored, you might want to look into inconsistent spacing between items and separators:
* tiny ugly gap between the first normal item and search box separator (and between the first favorite item and search box separator)
* bigger gap between the last favorite item and favorite box separator (and between the first normal item and the favorite box separator)

Dunno whether it should be big or tiny gaps or no gaps at all, but whatever the choice, it should be consistent :D

3) Also, due to the change of the font size when switching to regex mode and back, the search box changes its height which looks a bit jerky.

**Comment by SUPERCILEX** [comment]
I'm away from my computer for the next month and a half 😅 so won't be able to fix this anytime soon, but this is great attention to detail. Hopefully I'll get a chance to tweak it in October. :)

**Comment by SUPERCILEX** [comment]
Should all be fixed now!

**Comment by SUPERCILEX** [comment]
Released as 0.6.2, let me know what else you find. :)
