### ISSUE TITLE
Uninstallation script

### ISSUE THREAD

**Issue by HironTez** [SUPERCILEX/clipboard-history#38]
Hi. It would be nice to have an automatic uninstallation script.

**Comment by mrveress** [comment]
Absolutely true, not sure which packages need to remove and how - I'm new in Rust-related stuff, so not sure what exactly need to do with cargo etc.
Uninstall guide / script will be very nice!

**Comment by mrveress** [comment]
Not sure that this is correct, but for my Debian it have something like

`
systemctl --user disable ringboard-$XDG_SESSION_TYPE --now
systemctl --user daemon-reload
cargo uninstall clipboard-history
cargo uninstall clipboard-history-egui
cargo uninstall clipboard-history-server
cargo uninstall clipboard-history-x11
rm ~/.config/systemd/user/ringboard*
rm ~/.local/share/applications/ringboard*
rm ~/.local/share/icons/hicolor/1024x1024/ringboard*
`

But probably I missed something 😄

**Comment by SUPERCILEX** [comment]
Apologies for the delay! That was pretty much it, though you'll also want to disable the server.
